# defines automation services (optional)
services:
  frontend:
    name: Frontend Dev Server
    description: React frontend development server
    triggeredBy:
      - postEnvironmentStart
    commands:
      start: make frontend-dev
      ready: curl -s http://localhost:5173 > /dev/null
  backend:
    name: Backend Server
    description: Backend server
    triggeredBy:
      - postEnvironmentStart
    commands:
      start: make run
      ready: curl -s http://localhost:8081 > /dev/null

# defines automation tasks (optional)
tasks:
  dependencies:
    name: Run tests
    description: Run tests
    triggeredBy:
      - manual
    command: make test
  
  lint:
    name: Lint Code
    description: Run ESLint
    triggeredBy:
      - manual
    dependsOn:
      - dependencies
    command: cd frontend; npm run lint